### ISSUE TITLE
add topic proportions time series plot like papermachines

### ISSUE THREAD

**Issue by hugomailhot** [hugomailhot/corpus-explorer#36]
## Motivation

This is a great way to surface topic changes across time.

## Deliverable

Try and live up to this

![image](https://user-images.githubusercontent.com/5240492/71466950-2bfc8f00-278f-11ea-8705-cdb2288fb389.png)

## Subtasks

- [x] Compute topic volume time series
- [ ] Create legend that ties stacked topic area to most significant 3 words
- [x] Make stacked areas clickable so we can update the right-side view
- [x] Make left side of the app tabbed, so we can switch between inter-topic distance and topic volume time series

**Comment by hugomailhot** [comment]
This is only for later, but one cool idea could be to make the left side of the app (currently holding the intertopic distance scatter plot) a multi-tab zone, and we can switch between a view of topic distances and a view of the timeseries evolution. In both case we can still click on desired topics, and it updates the top topic term rankings on the right accordingly.

**Comment by hugomailhot** [comment]
Seeing how the stacked plot has different heights in different places, I assume that height represents either total text volume or document counts. The stacked values are not proportions, but rather they are both absolute values, either in terms of tokens attributable to a topic or documents attributable to a topic.

In the text volume case, we can do:
1. Compute the sum of doc_length * doc_topic_probability for each topic, for every time period
2. Stack the resulting values

In the document count case, we can do:
1. Add all doc_topic_probability values for each topic, for every time period
2. Stack the resulting values

**Comment by hugomailhot** [comment]
Check this out:

![image](https://user-images.githubusercontent.com/5240492/73722404-42c1ca00-46db-11ea-9b48-775bdf014644.png)

This is a topic volume time series plot for the Associated Press corpus using 15 topics. Very basic, but the information is all there.

One thing I discovered just now is that there are no articles for the year 1989 in that data set.

[Code is here](https://github.com/hugomailhot/corpus-explorer/blob/c1b8a67753d0009df3a00f168e3f02d7aeeab237/corpus_explorer/utils/nlp.py#L187-L234)

**Comment by hugomailhot** [comment]
Would be nice to have a data set that covers a larger time window, so that we can observe cool topic volume shifts like in that papermachines example.

**Comment by hugomailhot** [comment]
OK so I learned that the papermachines graph is called a stream graph, which is different from a stacked area chart like I've been doing. And we can do it in Plotly :fire: :fire: :fire: 

https://plot.ly/~dkoffler/1//#plot

![image](https://user-images.githubusercontent.com/5240492/75496617-f2a6f200-597e-11ea-831f-e9dd0fda453d.png)
